apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-zgib
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-zgib
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-zgib
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-zgib
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-zgib
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-zaza-tenant/nodejs-users/simple-nodejs-app-zgib@sha256:b47770666237f8031bae4cf40f7090537d19ab5c595f99b2d3fbdddbd12a1812
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
